---
# tasks file for /vagrant/ansible/roles/gitlab

- name: Install required dependencies
  ansible.builtin.apt:
    name:
      - curl
      - openssh-server
      - ca-certificates
      - tzdata
      - postfix
    state: present
    update_cache: yes

- name: Allow HTTP, HTTPS, and SSH traffic with UFW
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "80"
    - "443"
    - "22"

- name: Download GitLab repository installation script
  ansible.builtin.get_url:
    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
    dest: /tmp/gitlab_repo_script.sh
    mode: "0755"

- name: Execute GitLab repository script
  ansible.builtin.command:
    cmd: /tmp/gitlab_repo_script.sh
    creates: /etc/apt/sources.list.d/gitlab_gitlab-ce.list

- name: Install GitLab CE package
  ansible.builtin.apt:
    name: gitlab-ce
    state: present
    update_cache: yes

- name: Deploy gitlab.rb configuration file
  ansible.builtin.template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    mode: '0600'
  notify: Reconfigure GitLab
  
