---
gitlab_runner_container_name: gitlab-runner

gitlab_runner_name: gitlab-runner

gitlab_runner_image: gitlab/gitlab-runner:latest

gitlab_runner_restart_policy: always

gitlab_runner_config_volume: gitlab-runner-config

gitlab_runner_docker_socket: /var/run/docker.sock

gitlab_url: "http://{{ vm_private_ip }}"

gitlab_runner_tags: "docker"

gitlab_runner_executor: "docker"

docker_network: code-keeper