---
- name: Install GitLab
  hosts: all
  become: true
  roles:
    - role: commons
    - role: gitlab
    - role: gitlab_users

- name: Get GitLab Credentials
  hosts: all
  become: true
  roles:
    - role: gitlab_info