---
- name: Create GitLab Runner configuration volume
  community.docker.docker_volume:
    name: "{{ gitlab_runner_config_volume }}"

- name: Start GitLab Runner container
  community.docker.docker_container:
    name: "{{ gitlab_runner_container_name }}"
    image: "{{ gitlab_runner_image }}"
    state: started
    restart_policy: "{{ gitlab_runner_restart_policy }}"

    volumes:
      - "{{ gitlab_runner_config_volume }}:/etc/gitlab-runner"
      - "{{ gitlab_runner_docker_socket }}:/var/run/docker.sock"

- name: Ensure GitLab Runner token is provided
  assert:
    that:
      - gitlab_runner_token is defined
      - gitlab_runner_token | length > 0
    fail_msg: >
      gitlab_runner_token is missing.
      Store it in ansible/group_vars/vault.yml.

- name: Register GitLab Runner
  command: >
    docker exec {{ gitlab_runner_container_name }}
    gitlab-runner register
    --non-interactive
    --url {{ gitlab_url }}
    --token {{ gitlab_runner_token }}
    --executor {{ gitlab_runner_executor }}
    --docker-image {{ gitlab_runner_image }}
    --description {{ gitlab_runner_name }}